apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uwad4i3rn-go-gitops
  description: This is GitOps manifest for uwad4i3rn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=uwad4i3rn-go
    backstage.io/kubernetes-id: uwad4i3rn-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uwad4i3rn-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uwad4i3rn-go
