apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uwad4i3rn-go
  janus-idp.io/tekton: uwad4i3rn-go
  backstage.io/kubernetes-id: uwad4i3rn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uwad4i3rn-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
