apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uwad4i3rn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uwad4i3rn-go 
  name: uwad4i3rn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uwad4i3rn-go 
